services:
  - type: web
    name: smart-wallet-backend
    env: java
    buildCommand: "./mvnw clean install -DskipTests"
    startCommand: "java -jar backend/target/*.jar"
    plan: free
    region: singapore
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: smart-wallet-db
          property: connectionString
      - key: SERVER_PORT
        value: 10000

databases:
  - name: smart-wallet-db
    databaseName: smart_wallet_db
    user: smart_wallet_user
    plan: free
    region: singapore
