server:
  port: 8081
  error:
    include-message: always
    include-stacktrace: never

spring:
  application:
    name: smart-wallet-backend

  # PostgreSQL - financial data
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/smart_wallet_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    show-sql: false
  flyway:
    enabled: ${FLYWAY_ENABLED:false}  # temporarily disabled until Flyway version is aligned with PostgreSQL 14.20
    locations: classpath:db/migration
    baseline-on-migrate: true

  # MongoDB & Redis
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/smart_wallet_onboarding}
      database: ${MONGODB_DATABASE:smart_wallet_onboarding}
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  # SMTP Configuration (Brevo)
  mail:
    host: ${MAIL_HOST:smtp-relay.brevo.com}
    port: ${MAIL_PORT:465}
    username: ${MAIL_USERNAME:a60773001@smtp-brevo.com}
    password: ${MAIL_PASSWORD:xsmtpsib-eefb58650ee9def4ca18fcc3f0fe9ee031486f19181c2cb165d1e3b958f891ad-izQms3PHT7RvYNDY}
    properties:
      mail:
        debug: false
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

